package za.co.vortexit.pkg3.v0.autoshutdown;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Connor Lewis
 */
public class AutoShutdownGUI extends javax.swing.JFrame {

    private final javax.swing.ImageIcon scaledOnButtonPic;
    private final javax.swing.ImageIcon scaledOnButtonPressedPic;

    private final javax.swing.ImageIcon scaledOffButtonPic;
    private final javax.swing.ImageIcon scaledOffButtonPressedPic;

    private final Color BACKGROUND = new Color(30, 30, 30);
    private final Color FONT = new Color(73, 79, 91);

    /**
     * Creates new form AutoShutdownGUI
     */
    public AutoShutdownGUI() {
        initComponents();

        setIconImage(new javax.swing.ImageIcon("src/main/resources/icon.png").getImage().getScaledInstance(500, 500, Image.SCALE_SMOOTH));
        getContentPane().setBackground(BACKGROUND);

        javax.swing.ImageIcon onButtonPic = new javax.swing.ImageIcon("src/main/resources/on.png");
        scaledOnButtonPic = new javax.swing.ImageIcon(onButtonPic.getImage().getScaledInstance(btnKillSwitch.getPreferredSize().width, btnKillSwitch.getPreferredSize().height, Image.SCALE_SMOOTH));

        javax.swing.ImageIcon offButtonPic = new javax.swing.ImageIcon("src/main/resources/off.png");
        scaledOffButtonPic = new javax.swing.ImageIcon(offButtonPic.getImage().getScaledInstance(btnKillSwitch.getPreferredSize().width, btnKillSwitch.getPreferredSize().height, Image.SCALE_SMOOTH));

        javax.swing.ImageIcon onButtonPressedPic = new javax.swing.ImageIcon("src/main/resources/on_pressed.png");
        scaledOnButtonPressedPic = new javax.swing.ImageIcon(onButtonPressedPic.getImage().getScaledInstance(btnKillSwitch.getPreferredSize().width, btnKillSwitch.getPreferredSize().height, Image.SCALE_SMOOTH));

        javax.swing.ImageIcon offButtonPressedPic = new javax.swing.ImageIcon("src/main/resources/off_pressed.png");
        scaledOffButtonPressedPic = new javax.swing.ImageIcon(offButtonPressedPic.getImage().getScaledInstance(btnKillSwitch.getPreferredSize().width, btnKillSwitch.getPreferredSize().height, Image.SCALE_SMOOTH));

        btnKillSwitch.setIcon(scaledOnButtonPic);
        btnKillSwitch.setSelectedIcon(scaledOffButtonPic);

        cboTimeSelector.getEditor().getEditorComponent().setBackground(BACKGROUND);
        cboTimeSelector.getEditor().getEditorComponent().setForeground(FONT);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dlgAreaSearch = new javax.swing.JDialog();
        lblAreaSearchBarTitle = new javax.swing.JLabel();
        txfAreaSearchBar = new javax.swing.JTextField();
        cboTimeSelector = new javax.swing.JComboBox<>();
        pnlEventsPanel = new javax.swing.JPanel();
        lblEventsTitle = new javax.swing.JLabel();
        lblEvent1 = new javax.swing.JLabel();
        lblEvent2 = new javax.swing.JLabel();
        lblEvent3 = new javax.swing.JLabel();
        lblEvent4 = new javax.swing.JLabel();
        lblEvent5 = new javax.swing.JLabel();
        pnlCenterButtons = new javax.swing.JPanel();
        btnKillSwitch = new javax.swing.JButton();
        btnAreaSelector = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        dlgAreaSearch.setTitle("Search For Area");
        dlgAreaSearch.setAlwaysOnTop(true);
        dlgAreaSearch.setBackground(BACKGROUND);
        dlgAreaSearch.setBounds(new java.awt.Rectangle(0, 0, 350, 210));
        dlgAreaSearch.setLocation(new java.awt.Point(0, 0));
        dlgAreaSearch.setModal(true);
        dlgAreaSearch.setPreferredSize(new java.awt.Dimension(350, 210));
        dlgAreaSearch.setResizable(false);
        dlgAreaSearch.setType(java.awt.Window.Type.POPUP);
        dlgAreaSearch.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                dlgAreaSearchComponentHidden(evt);
            }
        });
        dlgAreaSearch.getContentPane().setLayout(new java.awt.GridBagLayout());

        lblAreaSearchBarTitle.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblAreaSearchBarTitle.setText("Enter Area Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        dlgAreaSearch.getContentPane().add(lblAreaSearchBarTitle, gridBagConstraints);

        txfAreaSearchBar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txfAreaSearchBar.setMinimumSize(new java.awt.Dimension(64, 30));
        txfAreaSearchBar.setPreferredSize(new java.awt.Dimension(140, 25));
        txfAreaSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfAreaSearchBarKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 26, 0);
        dlgAreaSearch.getContentPane().add(txfAreaSearchBar, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto Shutdown");
        setBackground(new java.awt.Color(30, 30, 30));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(51, 51, 51));
        setLocation(getLocation());
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        cboTimeSelector.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        cboTimeSelector.setForeground(new java.awt.Color(153, 153, 153));
        cboTimeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Minute", "2 Minutes", "3 Minutes", "4 Minutes" }));
        cboTimeSelector.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cboTimeSelector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(128, 2, 10, 12);
        getContentPane().add(cboTimeSelector, gridBagConstraints);

        pnlEventsPanel.setBackground(BACKGROUND);
        pnlEventsPanel.setLayout(new java.awt.GridBagLayout());

        lblEventsTitle.setBackground(BACKGROUND);
        lblEventsTitle.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblEventsTitle.setForeground(FONT);
        lblEventsTitle.setText("Upcoming Events: (Stage 0)");
        lblEventsTitle.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        pnlEventsPanel.add(lblEventsTitle, gridBagConstraints);

        lblEvent1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEvent1.setForeground(FONT);
        lblEvent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEvent1.setText("16:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 179);
        pnlEventsPanel.add(lblEvent1, gridBagConstraints);

        lblEvent2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEvent2.setForeground(FONT);
        lblEvent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEvent2.setText("16:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 179);
        pnlEventsPanel.add(lblEvent2, gridBagConstraints);

        lblEvent3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEvent3.setForeground(FONT);
        lblEvent3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEvent3.setText("16:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 179);
        pnlEventsPanel.add(lblEvent3, gridBagConstraints);

        lblEvent4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEvent4.setForeground(FONT);
        lblEvent4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEvent4.setText("16:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 179);
        pnlEventsPanel.add(lblEvent4, gridBagConstraints);

        lblEvent5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEvent5.setForeground(FONT);
        lblEvent5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEvent5.setText("16:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 179);
        pnlEventsPanel.add(lblEvent5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 39, 8);
        getContentPane().add(pnlEventsPanel, gridBagConstraints);

        pnlCenterButtons.setBackground(BACKGROUND);
        pnlCenterButtons.setLayout(new java.awt.GridBagLayout());

        btnKillSwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/on.png"))); // NOI18N
        btnKillSwitch.setToolTipText("Toggle shutdown feature");
        btnKillSwitch.setBorder(null);
        btnKillSwitch.setBorderPainted(false);
        btnKillSwitch.setContentAreaFilled(false);
        btnKillSwitch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKillSwitch.setFocusPainted(false);
        btnKillSwitch.setMaximumSize(new java.awt.Dimension(180, 180));
        btnKillSwitch.setMinimumSize(new java.awt.Dimension(180, 180));
        btnKillSwitch.setPreferredSize(new java.awt.Dimension(110, 110));
        btnKillSwitch.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/off.png"))); // NOI18N
        btnKillSwitch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKillSwitchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKillSwitchMouseReleased(evt);
            }
        });
        btnKillSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKillSwitchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 3.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 137, 0);
        pnlCenterButtons.add(btnKillSwitch, gridBagConstraints);

        btnAreaSelector.setBackground(BACKGROUND);
        btnAreaSelector.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAreaSelector.setForeground(FONT);
        btnAreaSelector.setBorder(null);
        btnAreaSelector.setBorderPainted(false);
        btnAreaSelector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAreaSelector.setFocusPainted(false);
        btnAreaSelector.setLabel("Area: ");
        btnAreaSelector.setMaximumSize(new java.awt.Dimension(160, 19));
        btnAreaSelector.setMinimumSize(new java.awt.Dimension(160, 19));
        btnAreaSelector.setPreferredSize(new java.awt.Dimension(160, 19));
        btnAreaSelector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAreaSelectorMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 3.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(232, 63, 231, 55);
        pnlCenterButtons.add(btnAreaSelector, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 141, 78, 47);
        getContentPane().add(pnlCenterButtons, gridBagConstraints);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(816, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKillSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKillSwitchActionPerformed
        System.out.println(btnKillSwitch.isSelected());
        btnKillSwitch.setSelected(!btnKillSwitch.isSelected());
    }//GEN-LAST:event_btnKillSwitchActionPerformed

    private void btnKillSwitchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKillSwitchMouseReleased

        btnKillSwitch.setIcon(scaledOnButtonPic);
        btnKillSwitch.setSelectedIcon(scaledOffButtonPic);
    }//GEN-LAST:event_btnKillSwitchMouseReleased

    private void btnKillSwitchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKillSwitchMousePressed

        btnKillSwitch.setSelectedIcon(scaledOffButtonPressedPic);
        btnKillSwitch.setIcon(scaledOnButtonPressedPic);
    }//GEN-LAST:event_btnKillSwitchMousePressed

    private void txfAreaSearchBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfAreaSearchBarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String input = txfAreaSearchBar.getText();
            
            System.out.println(input);
            
            dlgAreaSearch.setEnabled(false);
        }
    }//GEN-LAST:event_txfAreaSearchBarKeyPressed

    private void btnAreaSelectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAreaSelectorMouseClicked
        java.awt.Point p = getLocation();
        p.x += getWidth()/2-dlgAreaSearch.getWidth()/2;
        p.y += getHeight()/2-dlgAreaSearch.getHeight()/2;
        dlgAreaSearch.setLocation(p);
        dlgAreaSearch.setEnabled(true);
        dlgAreaSearch.setVisible(true);
        btnAreaSelector.setText("loading...");
    }//GEN-LAST:event_btnAreaSelectorMouseClicked

    private void dlgAreaSearchComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dlgAreaSearchComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgAreaSearchComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }

            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoShutdownGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AutoShutdownGUI().setVisible(true);
        });
        
        JSONManager testFile = new JSONManager(new String("{\"name\": \"Connor\"}"));
        testFile.setFile(new java.io.File("test"));
        testFile.writeFile("name", "boi");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAreaSelector;
    private javax.swing.JButton btnKillSwitch;
    private javax.swing.JComboBox<String> cboTimeSelector;
    private javax.swing.JDialog dlgAreaSearch;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAreaSearchBarTitle;
    private javax.swing.JLabel lblEvent1;
    private javax.swing.JLabel lblEvent2;
    private javax.swing.JLabel lblEvent3;
    private javax.swing.JLabel lblEvent4;
    private javax.swing.JLabel lblEvent5;
    private javax.swing.JLabel lblEventsTitle;
    private javax.swing.JPanel pnlCenterButtons;
    private javax.swing.JPanel pnlEventsPanel;
    private javax.swing.JTextField txfAreaSearchBar;
    // End of variables declaration//GEN-END:variables
}
